# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LTaxCloud
                                 A QGIS plugin
 This plugin upload gis data to server
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-09
        copyright            : (C) 2023 by Pongsak / SmartApp Services and Solutions Co.,Ltd
        email                : ltaxdev@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LTaxCloud class from file LTaxCloud.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .LTaxCloud import LTaxCloud
    return LTaxCloud(iface)
